apiVersion: "nextbreakpoint.com/v1"
kind: FlinkCluster
metadata:
  name: cluster-1
spec:
  supervisor:
    pullPolicy: Never
    image: nextbreakpoint/flinkctl:1.4.2-beta
    serviceAccount: flink-supervisor
    taskTimeout: 120
    resources:
      limits:
        cpu: '0.05'
        memory: 200Mi
      requests:
        cpu: '0.05'
        memory: 200Mi
  runtime:
    pullPolicy: Never
    image: example/flink:1.9.2
  jobManager:
    serviceMode: NodePort
    annotations:
      managed: true
    environment:
    - name: FLINK_JM_HEAP
      value: "256"
    - name: FLINK_SAVEPOINTS_LOCATION
      value: file:///var/savepoints
    - name: FLINK_CHECKPOINTS_LOCATION
      value: file:///var/checkpoints
    - name: FLINK_FS_CHECKPOINTS_LOCATION
      value: file:///var/fs_checkpoints
    - name: FLINK_S3_ENDPOINT
      value: http://minio-headless:9000
    - name: FLINK_S3_PATH_STYLE_ACCESS
      value: "true"
    environmentFrom:
    - secretRef:
        name: flink-secrets
    volumeMounts:
      - name: config-vol
        mountPath: /hadoop/etc/core-site.xml
        subPath: core-site.xml
      - name: data-vol
        mountPath: /data
    volumes:
      - name: config-vol
        configMap:
          name: flink-config
      - name: data-vol
        hostPath:
          path: /var/data
    initContainers:
      - image: busybox
        command:
          - ls
        imagePullPolicy: IfNotPresent
        name: initializer
        resources:
          limits:
            cpu: '0.2'
            memory: 128Mi
          requests:
            cpu: '0.1'
            memory: 64Mi
    sideContainers:
      - image: busybox
        command:
          - sleep
          - '3600'
        imagePullPolicy: IfNotPresent
        name: sidecar
        resources:
          limits:
            cpu: '0.2'
            memory: 128Mi
          requests:
            cpu: '0.1'
            memory: 64Mi
    extraPorts:
      - name: prometheus
        containerPort: 9999
        protocol: TCP
    resources:
      limits:
        cpu: '1'
        memory: 300Mi
      requests:
        cpu: '0.2'
        memory: 200Mi
  taskManager:
    taskSlots: 1
    annotations:
      managed: true
    environment:
    - name: FLINK_TM_HEAP
      value: "1024"
    - name: FLINK_SAVEPOINTS_LOCATION
      value: file:///var/savepoints
    - name: FLINK_CHECKPOINTS_LOCATION
      value: file:///var/checkpoints
    - name: FLINK_FS_CHECKPOINTS_LOCATION
      value: file:///var/fs_checkpoints
    - name: FLINK_S3_ENDPOINT
      value: http://minio-headless:9000
    - name: FLINK_S3_PATH_STYLE_ACCESS
      value: "true"
    environmentFrom:
      - secretRef:
          name: flink-secrets
    volumeMounts:
      - name: config-vol
        mountPath: /hadoop/etc/core-site.xml
        subPath: core-site.xml
      - name: data-vol
        mountPath: /data
    volumes:
      - name: config-vol
        configMap:
          name: flink-config
      - name: data-vol
        hostPath:
          path: /var/data
    initContainers:
      - image: busybox
        command:
          - ls
        imagePullPolicy: IfNotPresent
        name: initializer
        resources:
          limits:
            cpu: '0.2'
            memory: 128Mi
          requests:
            cpu: '0.1'
            memory: 64Mi
    sideContainers:
      - image: busybox
        command:
          - sleep
          - '3600'
        imagePullPolicy: IfNotPresent
        name: sidecar
        resources:
          limits:
            cpu: '0.2'
            memory: 128Mi
          requests:
            cpu: '0.1'
            memory: 64Mi
    extraPorts:
      - name: prometheus
        containerPort: 9999
        protocol: TCP
    resources:
      limits:
        cpu: '1'
        memory: 1100Mi
      requests:
        cpu: '0.2'
        memory: 600Mi
