apiVersion: "nextbreakpoint.com/v1"
kind: FlinkJob
metadata:
  name: test-job-1
spec:
  jobParallelism: 2
  savepoint:
    savepointMode: Automatic
    savepointInterval: 300
    savepointTargetPath: file:///var/savepoints
    restartPolicy: Always
  bootstrap:
    serviceAccount: flink-bootstrap
    pullPolicy: Never
    image: example/flink-jobs:1
    jarPath: /flink-jobs.jar
    className: com.nextbreakpoint.flink.jobs.stream.TestJob
    arguments:
      - --DEVELOP_MODE
      - disabled
    resources:
      limits:
        cpu: '0.05'
        memory: 200Mi
      requests:
        cpu: '0.05'
        memory: 200Mi
