apiVersion: "nextbreakpoint.com/v1"
kind: FlinkJob
metadata:
  name: cluster-1-job-2
spec:
  jobParallelism: 1
  savepoint:
    savepointMode: Manual
    savepointInterval: 0
    savepointTargetPath: file:///var/savepoints
  restart:
    restartPolicy: Never
    restartDelay: 60
    restartTimeout: 120
  bootstrap:
    serviceAccount: flink-bootstrap
    pullPolicy: Never
    image: example/jobs:latest
    jarPath: /flink-jobs.jar
    className: com.nextbreakpoint.flink.jobs.batch.ReportJob
    arguments:
      - --DEVELOP_MODE
      - disabled
    resources:
      limits:
        cpu: '0.05'
        memory: 200Mi
      requests:
        cpu: '0.05'
        memory: 200Mi
