---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flink-controller
subjects:
  - kind: ServiceAccount
    name: flink-controller
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flink-controller
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "services", "pods/portforward", "persistentvolumeclaims"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: ["beta.nextbreakpoint.com"]
    resources: ["flinkclusters"]
    verbs: ["get", "watch", "list"]
