{{- $fullname := include "minio.fullname" . -}}
{{- $name := include "minio.name" . -}}
{{- $chart := include "minio.chart" . -}}
{{- $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ $root.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        release: {{ $root.Release.Name }}
    spec:
      hostname: {{ $fullname }}
      initContainers:
        - image: busybox
          command:
            - mkdir
          args:
            - -p
            - /var/data
          imagePullPolicy: IfNotPresent
          name: initializer
          resources:
            limits:
              cpu: '0.2'
              memory: 64Mi
            requests:
              cpu: '0.05'
              memory: 16Mi
      containers:
        - name: {{ $root.Chart.Name }}
          image: "minio/minio:latest"
          imagePullPolicy: IfNotPresent
          args:
            - server
            - /var/data
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MINIO_ACCESS_KEY
              value: {{ $root.Values.minio.accessKey }}
            - name: MINIO_SECRET_KEY
              value: {{ $root.Values.minio.secretKey }}
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: '0.05'
              memory: 64Mi
