apiVersion: "nextbreakpoint.com/v1"
kind: FlinkCluster
metadata:
  name: test
spec:
  flinkImage:
    pullSecrets: regcred
    pullPolicy: IfNotPresent
    flinkImage: registry:30000/flink:1.7.2
  flinkJob:
    image: registry:30000/flink-jobs:1
    jarPath: /flink-jobs.jar
    className: com.nextbreakpoint.flink.jobs.TestJob
    parallelism: 1
    arguments:
      - --BUCKET_BASE_PATH
      - file:///var/tmp
  jobManager:
    serviceMode: NodePort
    storageClass: hostpath
    environment:
    - name: FLINK_GRAPHITE_HOST
      value: graphite.default.svc.cluster.local
    volumeMounts:
      - name: config-vol
        mountPath: /hadoop/etc/core-site.xml
        subPath: core-site.xml
      - name: config-vol
        mountPath: /docker-entrypoint.sh
        subPath: docker-entrypoint.sh
      - name: config-vol
        mountPath: /opt/flink/conf/flink-conf.yaml
        subPath: flink-conf.yaml
    volumes:
      - name: config-vol
        configMap:
          name: flink-config
          defaultMode: 0777
  taskManager:
    serviceMode: NodePort
    storageClass: hostpath
    environment:
    - name: FLINK_GRAPHITE_HOST
      value: graphite.default.svc.cluster.local
    volumeMounts:
      - name: config-vol
        mountPath: /hadoop/etc/core-site.xml
        subPath: core-site.xml
      - name: config-vol
        mountPath: /docker-entrypoint.sh
        subPath: docker-entrypoint.sh
      - name: config-vol
        mountPath: /opt/flink/conf/flink-conf.yaml
        subPath: flink-conf.yaml
    volumes:
      - name: config-vol
        configMap:
          name: flink-config
          defaultMode: 0777
  flinkOperator:
    targetPath: file:///var/tmp/test
