apiVersion: "nextbreakpoint.com/v1"
kind: FlinkCluster
metadata:
  name: test
spec:
  flinkImage:
    pullSecrets: regcred
    pullPolicy: IfNotPresent
    flinkImage: registry:30000/flink:1.7.2
  flinkJob:
    image: registry:30000/flink-jobs:1
    jarPath: /flink-jobs.jar
    className: com.nextbreakpoint.flink.jobs.TestJob
    parallelism: 1
    arguments:
      - --BUCKET_BASE_PATH
      - file:///var/tmp
  jobManager:
    serviceMode: NodePort
    storageClass: hostpath
    environment:
    - name: FLINK_GRAPHITE_HOST
      value: graphite.default.svc.cluster.local
  taskManager:
    serviceMode: NodePort
    storageClass: hostpath
    environment:
    - name: FLINK_GRAPHITE_HOST
      value: graphite.default.svc.cluster.local
  flinkOperator:
    targetPath: file:///var/tmp/test
