{{- $fullname := include "jobs.fullname" . -}}
{{- $name := include "jobs.name" . -}}
{{- $chart := include "jobs.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Values.name }}-aws-credentials-v1
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
type: Opaque
stringData:
  S3_ACCESS_KEY: {{ $root.Values.s3AccessKey }}
  S3_SECRET_KEY: {{ $root.Values.s3SecretKey }}
