{{- $fullname := include "jobs.fullname" . -}}
{{- $name := include "jobs.name" . -}}
{{- $chart := include "jobs.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.Values.name }}-flink-plugins-v1
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  ENABLE_BUILT_IN_PLUGINS: "flink-s3-fs-hadoop-{{ $root.Values.flinkVersion }}.jar;flink-s3-fs-presto-{{ $root.Values.flinkVersion }}.jar"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.Values.name }}-jobmanager-properties-v1
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  FLINK_PROPERTIES: |
    heartbeat.timeout: 90000
    heartbeat.interval: 15000
    jobmanager.memory.jvm-overhead.min: 64mb
    jobmanager.memory.jvm-metaspace.size: 192mb
    jobmanager.memory.off-heap.size: 64mb
    jobmanager.memory.process.size: 500mb
    jobmanager.memory.flink.size: 200mb
    metrics.reporters: prometheus
    metrics.reporter.prometheus.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prometheus.port: 9250
    metrics.latency.granularity: operator
    state.backend: filesystem
    s3.endpoint: {{ $root.Values.s3Endpoint }}
    s3.path.style.access: {{ $root.Values.s3PathStyleAccess }}
    s3.connection.maximum: 200
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.Values.name }}-taskmanager-properties-v1
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  FLINK_PROPERTIES: |
    heartbeat.timeout: 90000
    heartbeat.interval: 15000
    taskmanager.memory.jvm-overhead.min: 64mb
    taskmanager.memory.jvm-metaspace.size: 192mb
    taskmanager.memory.framework.heap.size: 64mb
    taskmanager.memory.framework.off-heap.size: 64mb
    taskmanager.memory.process.size: 600mb
    taskmanager.memory.flink.size: 300mb
    taskmanager.memory.network.fraction: 0.1
    taskmanager.memory.managed.fraction: 0.1
    metrics.reporters: prometheus
    metrics.reporter.prometheus.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prometheus.port: 9250
    metrics.latency.granularity: operator
    state.backend: filesystem
    s3.endpoint: {{ $root.Values.s3Endpoint }}
    s3.path.style.access: {{ $root.Values.s3PathStyleAccess }}
    s3.connection.maximum: 200
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Values.name }}-cluster-0-secret-v1
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
type: Opaque
stringData:
  SECRET_PROPERTIES: |
    s3.access-key: {{ $root.Values.s3AccessKey }}
    s3.secret-key: {{ $root.Values.s3SecretKey }}
    state.savepoints.dir: s3p://{{ $root.Values.s3BucketName }}/0/savepoints
    state.checkpoints.dir: s3p://{{ $root.Values.s3BucketName }}/0/checkpoints
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Values.name }}-cluster-1-secret-v1
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
type: Opaque
stringData:
  SECRET_PROPERTIES: |
    s3.access-key: {{ $root.Values.s3AccessKey }}
    s3.secret-key: {{ $root.Values.s3SecretKey }}
    state.savepoints.dir: s3p://{{ $root.Values.s3BucketName }}/1/savepoints
    state.checkpoints.dir: s3p://{{ $root.Values.s3BucketName }}/1/checkpoints
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Values.name }}-cluster-2-secret-v1
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
type: Opaque
stringData:
  SECRET_PROPERTIES: |
    s3.access-key: {{ $root.Values.s3AccessKey }}
    s3.secret-key: {{ $root.Values.s3SecretKey }}
    state.savepoints.dir: s3p://{{ $root.Values.s3BucketName }}/2/savepoints
    state.checkpoints.dir: s3p://{{ $root.Values.s3BucketName }}/2/checkpoints
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Values.name }}-cluster-3-secret-v1
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
type: Opaque
stringData:
  SECRET_PROPERTIES: |
    s3.access-key: {{ $root.Values.s3AccessKey }}
    s3.secret-key: {{ $root.Values.s3SecretKey }}
    state.savepoints.dir: s3p://{{ $root.Values.s3BucketName }}/3/savepoints
    state.checkpoints.dir: s3p://{{ $root.Values.s3BucketName }}/3/checkpoints
