FROM flink-k8s-toolbox:1.1.11-beta
RUN apk update && apk add wget
RUN wget -O flink-jobs.jar https://github.com/nextbreakpoint/flink-workshop/releases/download/v1.1.0/com.nextbreakpoint.flinkworkshop-1.1.0.jar
