{{- $fullname := include "flink-k8s-toolbox.fullname" . -}}
{{- $name := include "flink-k8s-toolbox.name" . -}}
{{- $chart := include "flink-k8s-toolbox.chart" . -}}
{{- $root := . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-operator
  {{- if $root.Values.namespace}}
  namespace: {{ $root.Values.namespace | quote }}
  {{- end}}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["nextbreakpoint.com"]
    resources: ["flinkclusters"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-upload
  {{- if $root.Values.namespace}}
  namespace: {{ $root.Values.namespace | quote }}
  {{- end}}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list"]
  - apiGroups: ["nextbreakpoint.com"]
    resources: ["flinkclusters"]
    verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-operator
  {{- if $root.Values.namespace}}
  namespace: {{ $root.Values.namespace | quote }}
  {{- end}}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-operator
  {{- if $root.Values.namespace}}
  namespace: {{ $root.Values.namespace | quote }}
  {{- end}}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-operator
subjects:
  - kind: ServiceAccount
    name: flink-operator
    namespace: {{ $root.Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-upload
  {{- if $root.Values.namespace}}
  namespace: {{ $root.Values.namespace | quote }}
  {{- end}}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-upload
  {{- if $root.Values.namespace}}
  namespace: {{ $root.Values.namespace | quote }}
  {{- end}}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-upload
subjects:
  - kind: ServiceAccount
    name: flink-upload
    namespace: {{ $root.Release.Namespace }}
