{{- $fullname := include "flink-k8s-toolbox.fullname" . -}}
{{- $name := include "flink-k8s-toolbox.name" . -}}
{{- $chart := include "flink-k8s-toolbox.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.name | default "flink-operator" | quote }}
  {{- if $root.Values.namespace}}
  namespace: {{ $root.Values.namespace | quote }}
  {{- end}}
  labels:
    app: {{ $root.Values.name | default "flink-operator" | quote }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $root.Values.service.ports.console | default 4444 }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ $root.Values.service.ports.metrics | default 8080 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: {{ $root.Values.name | default "flink-operator" | quote }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
