{{- $name := include "flink-k8s-toolbox.name" . -}}
{{- $chart := include "flink-k8s-toolbox.chart" . -}}
{{- $root := . }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: flinkclusters.nextbreakpoint.com
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  group: nextbreakpoint.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: flinkclusters
    singular: flinkcluster
    kind: FlinkCluster
    shortNames:
    - fc
  validation:
    openAPIV3Schema:
      type: object
      properties:
        status:
          type: object
          nullable: true
        spec:
          type: object
      required:
        - spec
  additionalPrinterColumns:
    - name: CLUSTER-STATUS
      type: string
      JSONPath: .status.clusterStatus
    - name: TASK-STATUS
      type: string
      JSONPath: .status.taskStatus
    - name: TASK
      type: string
      JSONPath: .status.tasks[0]
    - name: SAVEPOINT-PATH
      type: string
      JSONPath: .status.savepointPath
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
