# Default values for flink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nextbreakpoint/flink-k8s-toolbox
  tag: 1.0.2-alpha
  pullPolicy: Always
