{{- $fullname := include "flink-k8s-toolbox.fullname" . -}}
{{- $name := include "flink-k8s-toolbox.name" . -}}
{{- $chart := include "flink-k8s-toolbox.chart" . -}}
{{- $root := . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-operator
  namespace: {{ $root.Values.namespace | default $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["nextbreakpoint.com"]
    resources: ["flinkclusters"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["nextbreakpoint.com"]
    resources: ["flinkclusters/status", "flinkclusters/scale"]
    verbs: ["patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-operator
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-operator
  namespace: {{ $root.Values.namespace | default $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-operator
subjects:
  - kind: ServiceAccount
    name: flink-operator
    namespace: {{ $root.Release.Namespace | quote }}
