{{- $fullname := include "flink-k8s-toolbox.fullname" . -}}
{{- $name := include "flink-k8s-toolbox.name" . -}}
{{- $chart := include "flink-k8s-toolbox.chart" . -}}
{{- $root := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: flink-operator
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app: flink-operator
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
