# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nextbreakpoint/flinkctl
  tag: 1.4.4-beta
  pullPolicy: Always
  pullSecrets:

annotations:

strategy:
  type: Recreate

resources:
  requests:
    memory: "256Mi"
    cpu: "0.1"
  limits:
    memory: "256Mi"
    cpu: "1.0"

secretName:

serviceAccount: flink-operator

serviceType: ClusterIP
serviceNodePort:

keystore:
  pathKey: keystore.jks
  secretKey: keystore-secret

truststore:
  pathKey: truststore.jks
  secretKey: truststore-secret

taskTimeout: 120
pollingInterval: 10
