# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nextbreakpoint/flink-k8s-toolbox
  tag: 1.2.0-beta
  pullPolicy: Always

annotations:

strategy:
  type: Recreate

resources:
  requests:
    memory: "128Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "1000m"

secretName:

keystore:
  pathKey: keystore.jks
  secretKey: keystore-secret

truststore:
  pathKey: truststore.jks
  secretKey: truststore-secret
