apiVersion: "nextbreakpoint.com/v1"
kind: FlinkCluster
metadata:
  name: cluster-1
spec:
  taskManagers: 1
  runtime:
    pullPolicy: Never
    image: integration/flink:1.9.2
  bootstrap:
    serviceAccount: flink-bootstrap
    pullPolicy: Never
    image: integration/flink-jobs:1
    jarPath: /flink-jobs.jar
    className: com.nextbreakpoint.flink.jobs.stream.TestJob
    arguments:
      - --CONSOLE_OUTPUT
      - "true"
  jobManager:
    serviceMode: NodePort
    annotations:
      managed: true
    environment:
    - name: FLINK_JM_HEAP
      value: "256"
    - name: FLINK_ENVIRONMENT
      value: test
    - name: FLINK_GRAPHITE_HOST
      value: graphite.default.svc.cluster.local
    - name: FLINK_SAVEPOINTS_LOCATION
      value: s3a://flink/1/savepoints
    - name: FLINK_CHECKPOINTS_LOCATION
      value: file:///var/checkpoints
    - name: FLINK_FS_CHECKPOINTS_LOCATION
      value: file:///var/fs_checkpoints
    - name: FLINK_S3_ENDPOINT
      value: http://minio-headless:9000
    - name: FLINK_S3_ACCESS_KEY
      value: minioaccesskey
    - name: FLINK_S3_SECRET_KEY
      value: miniosecretkey
    - name: FLINK_S3_PATH_STYLE_ACCESS
      value: "true"
    environmentFrom:
    - secretRef:
        name: flink-secrets
    volumeMounts:
      - name: config-vol
        mountPath: /hadoop/etc/core-site.xml
        subPath: core-site.xml
      - name: config-vol
        mountPath: /docker-entrypoint.sh
        subPath: docker-entrypoint.sh
      - name: config-vol
        mountPath: /opt/flink/conf/flink-conf-template.yaml
        subPath: flink-conf.yaml
      - name: jobmanager
        mountPath: /var
    volumes:
      - name: config-vol
        configMap:
          name: flink-config
          defaultMode: 0777
    initContainers:
      - image: busybox
        command:
          - ls
        imagePullPolicy: IfNotPresent
        name: initializer
        resources:
          limits:
            cpu: '0.1'
            memory: 128Mi
          requests:
            cpu: '0.05'
            memory: 64Mi
    sideContainers:
      - image: busybox
        command:
          - sleep
          - '3600'
        imagePullPolicy: IfNotPresent
        name: sidecar
        resources:
          limits:
            cpu: '0.1'
            memory: 128Mi
          requests:
            cpu: '0.05'
            memory: 64Mi
    extraPorts:
      - name: prometheus
        containerPort: 9999
        protocol: TCP
    persistentVolumeClaimsTemplates:
      - metadata:
          name: jobmanager
        spec:
          storageClassName: standard
          accessModes:
           - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    resources:
      limits:
        cpu: '0.2'
        memory: 300Mi
      requests:
        cpu: '0.1'
        memory: 200Mi
  taskManager:
    taskSlots: 1
    annotations:
      managed: true
    environment:
    - name: FLINK_TM_HEAP
      value: "1024"
    - name: FLINK_ENVIRONMENT
      value: test
    - name: FLINK_GRAPHITE_HOST
      value: graphite.default.svc.cluster.local
    - name: FLINK_SAVEPOINTS_LOCATION
      value: s3a://flink/1/savepoints
    - name: FLINK_CHECKPOINTS_LOCATION
      value: file:///var/checkpoints
    - name: FLINK_FS_CHECKPOINTS_LOCATION
      value: file:///var/fs_checkpoints
    - name: FLINK_S3_ENDPOINT
      value: http://minio-headless:9000
    - name: FLINK_S3_ACCESS_KEY
      value: minioaccesskey
    - name: FLINK_S3_SECRET_KEY
      value: miniosecretkey
    - name: FLINK_S3_PATH_STYLE_ACCESS
      value: "true"
    volumeMounts:
      - name: config-vol
        mountPath: /hadoop/etc/core-site.xml
        subPath: core-site.xml
      - name: config-vol
        mountPath: /docker-entrypoint.sh
        subPath: docker-entrypoint.sh
      - name: config-vol
        mountPath: /opt/flink/conf/flink-conf-template.yaml
        subPath: flink-conf.yaml
      - name: taskmanager
        mountPath: /var
    volumes:
      - name: config-vol
        configMap:
          name: flink-config
          defaultMode: 0777
    initContainers:
      - image: busybox
        command:
          - ls
        imagePullPolicy: IfNotPresent
        name: initializer
        resources:
          limits:
            cpu: '0.1'
            memory: 128Mi
          requests:
            cpu: '0.05'
            memory: 64Mi
    sideContainers:
      - image: busybox
        command:
          - sleep
          - '3600'
        imagePullPolicy: IfNotPresent
        name: sidecar
        resources:
          limits:
            cpu: '0.1'
            memory: 128Mi
          requests:
            cpu: '0.05'
            memory: 64Mi
    extraPorts:
      - name: prometheus
        containerPort: 9999
        protocol: TCP
    persistentVolumeClaimsTemplates:
      - metadata:
          name: taskmanager
        spec:
          storageClassName: standard
          accessModes:
           - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
    resources:
      limits:
        cpu: '0.2'
        memory: 1100Mi
      requests:
        cpu: '0.1'
        memory: 600Mi
  operator:
    savepointMode: Manual
    savepointInterval: 20
    savepointTargetPath: s3a://flink/1/savepoints
    jobRestartPolicy: Always
