apiVersion: "nextbreakpoint.com/v1"
kind: FlinkDeployment
metadata:
  name: cluster-2
spec:
  jobs:
    - name: job-1
      spec:
        jobParallelism: 1
        savepoint:
          savepointMode: Automatic
          savepointInterval: 0
          savepointTargetPath: s3p://nextbreakpoint-integration/1/savepoints
        restart:
          restartPolicy: Never
          restartDelay: 60
          restartTimeout: 120
        bootstrap:
          serviceAccount: flink-bootstrap
          pullPolicy: Never
          image: integration/jobs:latest
          jarPath: /flink-jobs.jar
          className: com.nextbreakpoint.flink.jobs.ComputeAverage
          arguments:
            - --JOB_PARAMETERS
            - file:///var/config/computeaverage.conf
            - --OUTPUT_LOCATION
            - s3a://nextbreakpoint-integration/1
          resources:
            limits:
              cpu: '0.5'
              memory: 128Mi
            requests:
              cpu: '0.05'
              memory: 128Mi
    - name: job-2
      spec:
        jobParallelism: 2
        savepoint:
          savepointMode: Automatic
          savepointInterval: 0
          savepointTargetPath: s3p://nextbreakpoint-integration/1/savepoints
        restart:
          restartPolicy: Never
          restartDelay: 60
          restartTimeout: 120
        bootstrap:
          serviceAccount: flink-bootstrap
          pullPolicy: Never
          image: integration/jobs:latest
          jarPath: /flink-jobs.jar
          className: com.nextbreakpoint.flink.jobs.ComputeMaximum
          arguments:
            - --JOB_PARAMETERS
            - file:///var/config/computemaximum.conf
            - --OUTPUT_LOCATION
            - s3a://nextbreakpoint-integration/1
          resources:
            limits:
              cpu: '0.5'
              memory: 128Mi
            requests:
              cpu: '0.05'
              memory: 128Mi
  cluster:
    supervisor:
      pullPolicy: Never
      image: integration/flinkctl:1.4.4-beta
      serviceAccount: flink-supervisor
      taskTimeout: 180
      rescaleDelay: 30
      replicas: 2
      resources:
        limits:
          cpu: '1'
          memory: 128Mi
        requests:
          cpu: '0.05'
          memory: 128Mi
    runtime:
      pullPolicy: Never
      image: integration/flink:latest
    jobManager:
      serviceMode: ClusterIP
      annotations:
        managed: true
      command:
        - 'bash'
      args:
        - '-c'
        - 'FLINK_PROPERTIES="$(FLINK_PROPERTIES)$(SECRET_PROPERTIES)" /docker-entrypoint.sh jobmanager'
      environmentFrom:
        - configMapRef:
            name: integration-flink-plugins-v1
        - configMapRef:
            name: integration-jobmanager-properties-v1
        - secretRef:
            name: integration-cluster-2-secret-v1
      volumeMounts:
        - name: config-vol
          mountPath: /var/config/computeaverage.conf
          subPath: computeaverage.conf
        - name: config-vol
          mountPath: /var/config/computemaximum.conf
          subPath: computemaximum.conf
      volumes:
        - name: config-vol
          configMap:
            name: integration-job-parameters-v1
      resources:
        limits:
          cpu: '1'
          memory: 500Mi
        requests:
          cpu: '0.1'
          memory: 500Mi
    taskManager:
      taskSlots: 2
      annotations:
        managed: true
      command:
        - 'bash'
      args:
        - '-c'
        - 'FLINK_PROPERTIES="$(FLINK_PROPERTIES)$(SECRET_PROPERTIES)" /docker-entrypoint.sh taskmanager'
      environmentFrom:
        - configMapRef:
            name: integration-flink-plugins-v1
        - configMapRef:
            name: integration-taskmanager-properties-v1
        - secretRef:
            name: integration-cluster-2-secret-v1
      resources:
        limits:
          cpu: '1'
          memory: 600Mi
        requests:
          cpu: '0.05'
          memory: 600Mi
