apiVersion: "nextbreakpoint.com/v1"
kind: FlinkDeployment
metadata:
  name: cluster-1
spec:
  jobs:
    - name: job-0
      spec:
        jobParallelism: 1
        savepoint:
          savepointMode: Automatic
          savepointInterval: 0
          savepointTargetPath: s3a://nextbreakpoint-integration/savepoints
        restart:
          restartPolicy: Never
          restartDelay: 60
          restartTimeout: 120
        bootstrap:
          serviceAccount: flink-bootstrap
          pullPolicy: Never
          image: integration/jobs:latest
          jarPath: /flink-jobs.jar
          className: com.nextbreakpoint.flink.jobs.ComputeAverage
          arguments:
            - --JOB_PARAMETERS
            - /var/config/computeaverage.conf
            - --OUTPUT_LOCATION
            - s3a://nextbreakpoint-integration
          resources:
            limits:
              cpu: '1'
              memory: 200Mi
            requests:
              cpu: '0.1'
              memory: 200Mi
  cluster:
    supervisor:
      pullPolicy: Never
      image: integration/flinkctl:1.4.3-beta
      serviceAccount: flink-supervisor
      taskTimeout: 180
      rescaleDelay: 30
      replicas: 2
      resources:
        limits:
          cpu: '1'
          memory: 200Mi
        requests:
          cpu: '0.1'
          memory: 200Mi
    runtime:
      pullPolicy: Never
      image: integration/flink:1.11.3
    jobManager:
      serviceMode: NodePort
      annotations:
        managed: true
      command:
        - 'bash'
      args:
        - '-c'
        - 'FLINK_PROPERTIES="$(FLINK_PROPERTIES)\ns3.access-key: $(S3_ACCESS_KEY)\ns3.secret-key: $(S3_SECRET_KEY)" /docker-entrypoint.sh jobmanager'
      environment:
      environmentFrom:
        - configMapRef:
            name: integration-jobmanager-properties-v1
        - secretRef:
            name: integration-aws-credentials-v1
      initContainers:
        - image: busybox
          command:
            - ls
          imagePullPolicy: IfNotPresent
          name: initializer
          resources:
            limits:
              cpu: '0.5'
              memory: 128Mi
            requests:
              cpu: '0.1'
              memory: 64Mi
      sideContainers:
        - image: busybox
          command:
            - sleep
            - '3600'
          imagePullPolicy: IfNotPresent
          name: sidecar
          resources:
            limits:
              cpu: '0.5'
              memory: 128Mi
            requests:
              cpu: '0.1'
              memory: 64Mi
      extraPorts:
        - name: prometheus
          containerPort: 9250
          protocol: TCP
      volumeMounts:
        - name: config-vol
          mountPath: /var/config/computeaverage.conf
          subPath: computeaverage.conf
      volumes:
        - name: config-vol
          configMap:
            name: integration-job-parameters-v1
      resources:
        limits:
          cpu: '1'
          memory: 600Mi
        requests:
          cpu: '0.1'
          memory: 128Mi
    taskManager:
      taskSlots: 1
      annotations:
        managed: true
      command:
        - 'bash'
      args:
        - '-c'
        - 'FLINK_PROPERTIES="$(FLINK_PROPERTIES)\ns3.access-key: $(S3_ACCESS_KEY)\ns3.secret-key: $(S3_SECRET_KEY)" /docker-entrypoint.sh taskmanager'
      environmentFrom:
        - configMapRef:
            name: integration-taskmanager-properties-v1
        - secretRef:
            name: integration-aws-credentials-v1
      initContainers:
        - image: busybox
          command:
            - ls
          imagePullPolicy: IfNotPresent
          name: initializer
          resources:
            limits:
              cpu: '0.5'
              memory: 128Mi
            requests:
              cpu: '0.1'
              memory: 64Mi
      sideContainers:
        - image: busybox
          command:
            - sleep
            - '3600'
          imagePullPolicy: IfNotPresent
          name: sidecar
          resources:
            limits:
              cpu: '0.5'
              memory: 128Mi
            requests:
              cpu: '0.1'
              memory: 64Mi
      extraPorts:
        - name: prometheus
          containerPort: 9250
          protocol: TCP
      resources:
        limits:
          cpu: '1'
          memory: 600Mi
        requests:
          cpu: '0.1'
          memory: 256Mi
