apiVersion: "nextbreakpoint.com/v1"
kind: FlinkDeployment
metadata:
  name: cluster-2
spec:
  jobs:
    - name: job-1
      spec:
        jobParallelism: 1
        savepoint:
          savepointMode: Automatic
          savepointInterval: 0
          savepointTargetPath: s3a://flink/2/savepoints
        restart:
          restartPolicy: Never
          restartDelay: 60
          restartTimeout: 120
        bootstrap:
          serviceAccount: flink-bootstrap
          pullPolicy: Never
          image: integration/jobs:latest
          jarPath: /flink-jobs.jar
          className: com.nextbreakpoint.flink.jobs.stream.TestJob
          arguments:
            - --CONSOLE_OUTPUT
            - "false"
          resources:
            limits:
              cpu: '1'
              memory: 200Mi
            requests:
              cpu: '0.1'
              memory: 200Mi
    - name: job-2
      spec:
        jobParallelism: 2
        savepoint:
          savepointMode: Automatic
          savepointInterval: 0
          savepointTargetPath: s3a://flink/2/savepoints
        restart:
          restartPolicy: Never
          restartDelay: 60
          restartTimeout: 120
        bootstrap:
          serviceAccount: flink-bootstrap
          pullPolicy: Never
          image: integration/jobs:latest
          jarPath: /flink-jobs.jar
          className: com.nextbreakpoint.flink.jobs.stream.TestJob
          arguments:
            - --CONSOLE_OUTPUT
            - "false"
          resources:
            limits:
              cpu: '1'
              memory: 200Mi
            requests:
              cpu: '0.1'
              memory: 200Mi
  cluster:
    supervisor:
      pullPolicy: Never
      image: integration/flinkctl:1.4.3-beta
      serviceAccount: flink-supervisor
      taskTimeout: 180
      rescaleDelay: 30
      replicas: 2
      resources:
        limits:
          cpu: '1'
          memory: 200Mi
        requests:
          cpu: '0.1'
          memory: 200Mi
    runtime:
      pullPolicy: Never
      image: integration/flink:1.9.2
    jobManager:
      serviceMode: ClusterIP
      annotations:
        managed: true
      environment:
        - name: FLINK_JM_HEAP
          value: "256"
        - name: FLINK_SAVEPOINTS_LOCATION
          value: s3a://flink/2/savepoints
        - name: FLINK_CHECKPOINTS_LOCATION
          value: file:///var/checkpoints
        - name: FLINK_FS_CHECKPOINTS_LOCATION
          value: file:///var/fs_checkpoints
        - name: FLINK_S3_ENDPOINT
          value: http://minio-headless:9000
        - name: FLINK_S3_PATH_STYLE_ACCESS
          value: "true"
      environmentFrom:
        - secretRef:
            name: flink-secrets
      volumeMounts:
        - name: config-vol
          mountPath: /hadoop/etc/core-site.xml
          subPath: core-site.xml
        - name: data-vol
          mountPath: /data
      volumes:
        - name: config-vol
          configMap:
            name: flink-config
        - name: data-vol
          hostPath:
            path: /data
      resources:
        limits:
          cpu: '1'
          memory: 300Mi
        requests:
          cpu: '0.1'
          memory: 200Mi
    taskManager:
      taskSlots: 2
      annotations:
        managed: true
      environment:
        - name: FLINK_TM_HEAP
          value: "400"
        - name: FLINK_SAVEPOINTS_LOCATION
          value: s3a://flink/2/savepoints
        - name: FLINK_CHECKPOINTS_LOCATION
          value: file:///var/checkpoints
        - name: FLINK_FS_CHECKPOINTS_LOCATION
          value: file:///var/fs_checkpoints
        - name: FLINK_S3_ENDPOINT
          value: http://minio-headless:9000
        - name: FLINK_S3_PATH_STYLE_ACCESS
          value: "true"
      environmentFrom:
        - secretRef:
            name: flink-secrets
      volumeMounts:
        - name: config-vol
          mountPath: /hadoop/etc/core-site.xml
          subPath: core-site.xml
        - name: data-vol
          mountPath: /data
      volumes:
        - name: config-vol
          configMap:
            name: flink-config
        - name: data-vol
          hostPath:
            path: /data
      resources:
        limits:
          cpu: '1'
          memory: 500Mi
        requests:
          cpu: '0.1'
          memory: 500Mi
