{{- $fullname := include "demo.fullname" . -}}
{{- $name := include "demo.name" . -}}
{{- $chart := include "demo.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.Values.name }}-jobmanager-properties-v1
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  FLINK_PROPERTIES: |
    heartbeat.timeout: 90000
    heartbeat.interval: 15000
    jobmanager.memory.jvm-overhead.min: 64mb
    jobmanager.memory.jvm-metaspace.size: 192mb
    jobmanager.memory.off-heap.size: 64mb
    jobmanager.memory.process.size: 600mb
    jobmanager.memory.flink.size: 256mb
    metrics.reporters: prometheus
    metrics.reporter.prometheus.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prometheus.port: 9250
    metrics.latency.granularity: operator
    state.backend: filesystem
    state.savepoints.dir: s3a://{{ $root.Values.s3BucketName }}/savepoints
    state.checkpoints.dir: s3a://{{ $root.Values.s3BucketName }}/checkpoints
    s3.connection.maximum: 200
    {{- if $root.Values.s3Endpoint }}
    s3.endpoint: {{ $root.Values.s3Endpoint }}
    {{- end }}
    {{- if $root.Values.s3PathStyleAccess }}
    s3.path.style.access: {{ $root.Values.s3PathStyleAccess }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.Values.name }}-taskmanager-properties-v1
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
  FLINK_PROPERTIES: |
    heartbeat.timeout: 90000
    heartbeat.interval: 15000
    taskmanager.memory.jvm-overhead.min: 192mb
    taskmanager.memory.jvm-metaspace.size: 256mb
    taskmanager.memory.framework.heap.size: 128mb
    taskmanager.memory.framework.off-heap.size: 128mb
    taskmanager.memory.process.size: 2200mb
    taskmanager.memory.flink.size: 1600mb
    taskmanager.memory.network.fraction: 0.1
    taskmanager.memory.managed.fraction: 0.1
    metrics.reporters: prometheus
    metrics.reporter.prometheus.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prometheus.port: 9250
    metrics.latency.granularity: operator
    state.backend: filesystem
    state.savepoints.dir: s3a://{{ $root.Values.s3BucketName }}/savepoints
    state.checkpoints.dir: s3a://{{ $root.Values.s3BucketName }}/checkpoints
    s3.connection.maximum: 200
    {{- if $root.Values.s3Endpoint }}
    s3.endpoint: {{ $root.Values.s3Endpoint }}
    {{- end }}
    {{- if $root.Values.s3PathStyleAccess }}
    s3.path.style.access: {{ $root.Values.s3PathStyleAccess }}
    {{- end }}
