name: Flink Kubernetes Toolbox
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Print dependencies
      run: pipeline/print-dependencies.sh
    - name: Start Minikube
      run: pipeline/run-minikube.sh
    - name: Docker login
      if: github.event_name == 'release' && github.event.action == 'published'
      run: pipeline/docker-login.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker images
      run: pipeline/docker-build-images.sh
    - name: Run integration tests
      run: pipeline/run-integration-tests.sh
    - name: Publish to Registry
      if: github.event_name == 'release' && github.event.action == 'published'
      run: pipeline/docker-push-image.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE_TAG: ${{ github.event.release.name }}
