name: Flink Operator CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Docker
      run: sh pipeline/setup-docker.sh
    - name: Set up Minikube
      run: sh pipeline/setup-minikube.sh
    - name: Set up Kube
      run: sh pipeline/setup-kube.sh
    - name: Set up Helm
      run: sh pipeline/setup-helm.sh
    - name: Build and run unit tests
      run: ./gradlew test
    - name: Run integration tests
      run: ./gradlew integrationTest
