name: Flink Operator CI
on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Docker
      run: pipeline/install-docker.sh
    - name: Install Minikube
      run: pipeline/install-minikube.sh
    - name: Start Minikube
      run: pipeline/run-minikube.sh
    - name: Build operator
      run: pipeline/build-docker-images.sh
    - name: Install Kubectl
      run: pipeline/install-kubectl.sh
    - name: Install Helm
      run: pipeline/install-helm.sh
    - name: Run integration test - EnsureBehaviour
      run: pipeline/run-integration-test.sh EnsureBehaviour
