name: Flink Operator CI
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Print Java version
      run: pipeline/print-java-version.sh
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
    - name: Print dependencies
      run: pipeline/print-dependencies.sh
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
    - name: Start Minikube
      run: pipeline/run-minikube.sh
    - name: Build Docker images
      run: pipeline/docker-build-images.sh
    - name: Run integration test - EnsureBehaviour
      run: pipeline/run-integration-test.sh EnsureBehaviour
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
    - name: Publish to Registry
      if: github.event_name == 'release' && github.event.action == 'published'
      run: pipeline/docker-push-image.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE_TAG: ${{ github.event.release.name }}
